#!/bin/bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

playlist=$1

if [ "$playlist" == "" ]; then
    ytid_arr="$(sqlite3 "$script_dir/youtube_stuffs.db" "select id from ytlist")"
else
    ytid_arr="$(sqlite3 "$script_dir/youtube_stuffs.db" "select id from ytlist where category='$playlist'")"
fi


printf "# yt list gen\n\n" > ytlist.md
printf "# yt list gen\n\n" > ytlist-thumb.md

for ytid in $ytid_arr; do
    item="$(sqlite3 -- "$script_dir/youtube_stuffs.db" "select rowid,title from ytlist where id='$ytid'" | sed 's/*/\\*/g')"
    thumb="$(find -- $script_dir/thumbnails/$ytid*)"
    printf -- "- [%s](https://youtube.com/watch?v=%s)\n" "$item" "$ytid" >> ytlist.md
    printf -- "- [%s](https://youtube.com/watch?v=%s)\n     - ![thumb](%s)\n" "$item" "$ytid" "$thumb" >> ytlist-thumb.md
done
